### PR TITLE
fix: empty object generation

### LINKED ISSUE #336: Anonymous class with syntax error
It generates an annonimous class with syntax error, if the payload is defined as such;

        payload:
          description: bla bla
          type: object

the created annonimous class is;

```
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.annotation.processing.Generated;
import java.util.List;
import java.util.Objects;

@Generated(value="com.asyncapi.generator.template.spring", date="2023-10-11T07:43:58.414Z")
public class AnonymousSchema9 {
    

    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AnonymousSchema9 anonymousSchema9 = (AnonymousSchema9) o;
        return 
    }

    @Override
    public int hashCode() {
        return Objects.hash();
    }

    @Override
    public String toString() {
        return "class AnonymousSchema9 {\n" +
        
                "}";
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
           return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }
}  
```

AnonymousSchema9 anonymousSchema9 = (AnonymousSchema9) o;
        **return**

### PR DESCRIPTION
**Pull request by Tenischev**
**Description**

- If schema object has no properties it's hashCode and equals methods will rely on `super` 

**Related issue(s)**
Fixes #336

### CODE REVIEW

**Comment by Tenischev** [comment]
@khalender , @derberg please have a look

File: template/src/main/java/com/asyncapi/model/$$objectSchema$$.java [hunk 1]
```diff
@@ -158,6 +158,9 @@ public class {{allName}} {
     {% endfor %}
     {% if params.disableEqualsHashCode === 'false' %}@Override
     public boolean equals(Object o) {
+    {%- if schema.properties() | length === 0 %}
```
Comment (derberg) [inline template/src/main/java/com/asyncapi/model/$$objectSchema$$.java:161]: since you use `schema.properties() | length === 0` twice in this template, you can define one set for it, like for example in https://github.com/asyncapi/java-spring-template/blob/master/partials/KafkaConfig.java#L2

**Review by derberg — APPROVED** [review]
